### ISSUE TITLE
documentation: Add strawberry pearl dependency 

### ISSUE THREAD

**Issue by Sean1572** [UCSD-E4E/weekly_presentations#14]
When using with vscode, make sure to install pearl

**Comment by ntlhui** [comment]
Why do we need this?

**Comment by ntlhui** [comment]
@Sean1572 can you elaborate on the pearl extension?  I can't seem to find it on the VS Code marketplace

**Comment by ntlhui** [comment]
@Sean1572 please elaborate on the pearl extension.

**Comment by ntlhui** [comment]
Closing this, since there are no further input
