### ISSUE TITLE
git repo takes too long to download/is too large

### ISSUE THREAD

**Issue by ccrutchf** [UCSD-E4E/weekly_presentations#75]
Windows gave an initial connection timed out when downloading.  The repo is 160mb.

**Comment by ntlhui** [comment]
Recommend cloning `--filter=blob:none`

e.g. `git clone --filter=blob:none git@github.com:UCSD-E4E/weekly_presentations.git`

See https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/#user-content-blobless-clones
